[package]
name = "project_comet_client"
version = "0.1.0"
authors = ["Lucy Awrey <lucyawrey@gmail.com>"]
edition = "2021"

[dependencies]
wasm-bindgen = { version = "= 0.2.100" }
bevy = { version = "0.15.2", features = ["dynamic_linking"] }
serde = "1.0.217"
serde_json = "1.0.138"
#rusqlite = { version = "0.33.0", features = ["bundled", "wasm32-wasi-vfs"] }

# Enable only a small amount of optimization in debug mode.
[profile.dev]
opt-level = 1

# Enable max optimizations for dependencies, but not for our code.
[profile.dev.package."*"]
opt-level = 3

# Enable more optimization in the release profile at the cost of compile time.
[profile.release]
lto = true
opt-level = 3
codegen-units = 1
incremental = false
debug = false

[profile.wasm-release]
inherits = "release"
strip = "debuginfo"
